/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/signup": {
    post: operations["signup"];
  };
  "/auth/login": {
    post: operations["login"];
  };
  "/auth/refresh": {
    post: operations["refreshToken"];
  };
  "/auth/logout": {
    post: operations["logout"];
  };
  "/auth/google/authorize": {
    get: operations["getGoogleAuthUrl"];
  };
  "/auth/google/callback": {
    get: operations["handleGoogleCallback"];
  };
  "/venues": {
    get: operations["getVenues"];
  };
  "/events": {
    get: operations["getEvents"];
  };
  "/events/{event_id}/showtimes": {
    get: operations["getShowtimesByEvent"];
  };
  "/showtimes/{show_id}": {
    get: operations["getShowtime"];
  };
  "/showtimes/{show_id}/seats": {
    get: operations["getSeatMap"];
  };
  "/queue/join": {
    post: operations["joinQueue"];
  };
  "/queue/status": {
    get: operations["getQueueStatus"];
  };
  "/queue/recover": {
    get: operations["recoverQueue"];
  };
  "/seats/lock": {
    post: operations["lockSeats"];
  };
  "/book": {
    post: operations["bookSeats"];
  };
  "/book/{booking_id}/mock-confirm": {
    post: operations["mockConfirm"];
  };
  "/bookings": {
    get: operations["getUserBookings"];
  };
  "/payments/intent": {
    post: operations["createPaymentIntent"];
  };
  "/admin/events": {
    post: operations["adminCreateEvent"];
  };
  "/admin/events/{event_id}": {
    delete: operations["adminDeleteEvent"];
  };
  "/admin/venues": {
    post: operations["adminCreateVenue"];
  };
  "/admin/venues/{venue_id}": {
    delete: operations["adminDeleteVenue"];
  };
  "/admin/showtimes": {
    get: operations["adminGetShowtimes"];
    post: operations["adminCreateShowtime"];
  };
  "/admin/showtimes/{show_id}": {
    delete: operations["adminDeleteShowtime"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SignupRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    SignupResponse: {
      /** Format: uuid */
      user_id: string;
      email: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    LoginResponse: {
      access_token: string;
      refresh_token: string;
      /** @default bearer */
      token_type: string;
      /** @default false */
      is_admin: boolean;
    };
    RefreshRequest: {
      refresh_token: string;
    };
    OAuthAuthorizeResponse: {
      authorize_url: string;
      state: string;
    };
    VenueResponse: {
      /** Format: uuid */
      venue_id: string;
      name: string;
      capacity: number;
    };
    EventResponse: {
      event_id: string;
      /** @enum {string} */
      event_type: "MOVIE" | "EVENT";
      name: string;
      description: string | null;
    };
    ShowtimeResponse: {
      /** Format: uuid */
      show_id: string;
      event_id: string;
      /** Format: uuid */
      venue_id: string;
      base_price: string;
      /** Format: date-time */
      start_time: string;
      /** Format: date-time */
      end_time: string;
    };
    SeatResponse: {
      seat_id: string;
      tier: string;
      price: string;
      /** @enum {string} */
      status: "AVAILABLE" | "PENDING_PAYMENT" | "SOLD";
    };
    SeatMapResponse: {
      /** Format: uuid */
      show_id: string;
      seats: components["schemas"]["SeatResponse"][];
    };
    QueueJoinRequest: {
      /** Format: uuid */
      show_id: string;
    };
    QueueJoinResponse: {
      queue_token: string | null;
      position: number;
      /** @enum {string} */
      status: "waiting" | "admitted";
    };
    QueueStatusResponse: {
      position: number | null;
      /** @enum {string} */
      status: "waiting" | "admitted" | "expired";
      retry_after: number | null;
      queue_token: string | null;
    };
    QueueRecoverResponse: {
      queue_token: string | null;
      /** @enum {string} */
      status: "admitted" | "none";
    };
    SeatLockRequest: {
      /** Format: uuid */
      show_id: string;
      seat_ids: string[];
    };
    SeatLockResponse: {
      idempotency_key: string;
      /** Format: date-time */
      expires_at: string;
      locked_seat_ids: string[];
    };
    BookRequest: {
      /** Format: uuid */
      show_id: string;
      seat_ids: string[];
      idempotency_key: string;
    };
    BookResponse: {
      /** Format: uuid */
      booking_id: string;
      status: string;
      /** Format: date-time */
      expires_at: string;
    };
    MockConfirmResponse: {
      /** Format: uuid */
      booking_id: string;
      status: string;
      seat_ids: string[];
    };
    BookingSeatInfo: {
      seat_id: string;
      tier: string;
      price: string;
    };
    BookingListItem: {
      booking_id: string;
      status: string;
      seats: components["schemas"]["BookingSeatInfo"][];
      amount: string;
      currency: string;
      created_at: string | null;
      show_id: string;
      start_time: string | null;
      end_time: string | null;
      event_name: string;
      venue_name: string;
    };
    PaymentIntentRequest: {
      /** Format: uuid */
      booking_id: string;
    };
    PaymentIntentResponse: {
      /** Format: uuid */
      payment_id: string;
      client_secret: string;
      status: string;
    };
    EventCreateRequest: {
      /** @enum {string} */
      event_type: "MOVIE" | "EVENT";
      name: string;
      description?: string;
    };
    VenueCreateRequest: {
      name: string;
      capacity: number;
    };
    ShowtimeCreateRequest: {
      event_id: string;
      venue_id: string;
      base_price: number;
      /** Format: date-time */
      start_time: string;
      /** Format: date-time */
      end_time: string;
      /** @default true */
      auto_seats?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  signup: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      /** @description User created */
      200: {
        content: {
          "application/json": components["schemas"]["SignupResponse"];
        };
      };
    };
  };
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  refreshToken: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Token refreshed */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  logout: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Logged out */
      200: {
        content: never;
      };
    };
  };
  getGoogleAuthUrl: {
    responses: {
      /** @description Google OAuth URL */
      200: {
        content: {
          "application/json": components["schemas"]["OAuthAuthorizeResponse"];
        };
      };
    };
  };
  handleGoogleCallback: {
    parameters: {
      query: {
        code: string;
        state: string;
      };
    };
    responses: {
      /** @description Google login successful */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  getVenues: {
    responses: {
      /** @description List of venues */
      200: {
        content: {
          "application/json": components["schemas"]["VenueResponse"][];
        };
      };
    };
  };
  getEvents: {
    responses: {
      /** @description List of events */
      200: {
        content: {
          "application/json": components["schemas"]["EventResponse"][];
        };
      };
    };
  };
  getShowtimesByEvent: {
    parameters: {
      path: {
        event_id: string;
      };
    };
    responses: {
      /** @description List of showtimes */
      200: {
        content: {
          "application/json": components["schemas"]["ShowtimeResponse"][];
        };
      };
    };
  };
  getShowtime: {
    parameters: {
      path: {
        show_id: string;
      };
    };
    responses: {
      /** @description Showtime details */
      200: {
        content: {
          "application/json": components["schemas"]["ShowtimeResponse"];
        };
      };
    };
  };
  getSeatMap: {
    parameters: {
      path: {
        show_id: string;
      };
    };
    responses: {
      /** @description Seat map for showtime */
      200: {
        content: {
          "application/json": components["schemas"]["SeatMapResponse"];
        };
      };
    };
  };
  joinQueue: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["QueueJoinRequest"];
      };
    };
    responses: {
      /** @description Queue join result */
      200: {
        content: {
          "application/json": components["schemas"]["QueueJoinResponse"];
        };
      };
    };
  };
  getQueueStatus: {
    parameters: {
      query: {
        show_id: string;
      };
    };
    responses: {
      /** @description Queue status */
      200: {
        content: {
          "application/json": components["schemas"]["QueueStatusResponse"];
        };
      };
    };
  };
  recoverQueue: {
    parameters: {
      query: {
        show_id: string;
      };
    };
    responses: {
      /** @description Queue recovery info */
      200: {
        content: {
          "application/json": components["schemas"]["QueueRecoverResponse"];
        };
      };
    };
  };
  lockSeats: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SeatLockRequest"];
      };
    };
    responses: {
      /** @description Seat lock confirmation */
      200: {
        content: {
          "application/json": components["schemas"]["SeatLockResponse"];
        };
      };
    };
  };
  bookSeats: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookRequest"];
      };
    };
    responses: {
      /** @description Booking initialized */
      200: {
        content: {
          "application/json": components["schemas"]["BookResponse"];
        };
      };
    };
  };
  mockConfirm: {
    parameters: {
      path: {
        booking_id: string;
      };
    };
    responses: {
      /** @description Booking confirmed (demo) */
      200: {
        content: {
          "application/json": components["schemas"]["MockConfirmResponse"];
        };
      };
    };
  };
  getUserBookings: {
    responses: {
      /** @description User bookings */
      200: {
        content: {
          "application/json": components["schemas"]["BookingListItem"][];
        };
      };
    };
  };
  createPaymentIntent: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaymentIntentRequest"];
      };
    };
    responses: {
      /** @description Payment intent created */
      200: {
        content: {
          "application/json": components["schemas"]["PaymentIntentResponse"];
        };
      };
    };
  };
  adminCreateEvent: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventCreateRequest"];
      };
    };
    responses: {
      /** @description Event created */
      201: {
        content: {
          "application/json": components["schemas"]["EventResponse"];
        };
      };
    };
  };
  adminDeleteEvent: {
    parameters: {
      path: {
        event_id: string;
      };
    };
    responses: {
      /** @description Event deleted */
      200: {
        content: never;
      };
    };
  };
  adminCreateVenue: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VenueCreateRequest"];
      };
    };
    responses: {
      /** @description Venue created */
      201: {
        content: {
          "application/json": components["schemas"]["VenueResponse"];
        };
      };
    };
  };
  adminDeleteVenue: {
    parameters: {
      path: {
        venue_id: string;
      };
    };
    responses: {
      /** @description Venue deleted */
      200: {
        content: never;
      };
    };
  };
  adminGetShowtimes: {
    responses: {
      /** @description All showtimes */
      200: {
        content: {
          "application/json": components["schemas"]["ShowtimeResponse"][];
        };
      };
    };
  };
  adminCreateShowtime: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShowtimeCreateRequest"];
      };
    };
    responses: {
      /** @description Showtime created */
      201: {
        content: {
          "application/json": components["schemas"]["ShowtimeResponse"];
        };
      };
    };
  };
  adminDeleteShowtime: {
    parameters: {
      path: {
        show_id: string;
      };
    };
    responses: {
      /** @description Showtime deleted */
      200: {
        content: never;
      };
    };
  };
}
