apiVersion: v1
kind: Secret
metadata:
  name: event-ticketing-secrets
  namespace: event-ticketing
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://testuser:testpass@postgres:5432/event_ticketing"
  REDIS_URL: "redis://redis:6379/0"
  CORS_ORIGINS: "http://localhost"
  CLIENT_ORIGIN: "http://localhost"
  LOG_FORMAT: "console"
  LOG_LEVEL: "INFO"
