apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: event-ticketing

resources:
  - namespace.yaml
  - network-policies.yaml
  - gateway-api-deployment.yaml
  - gateway-api-service.yaml
  - gateway-web-deployment.yaml
  - gateway-service.yaml
  - pdb.yaml
  - hpa.yaml
  - sweeper-deployment.yaml
  - relay-deployment.yaml
  - admitter-deployment.yaml
  - migration-job.yaml
  - keda-queue-scaler.yaml
