apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-only
  namespace: event-ticketing
  labels:
    app.kubernetes.io/part-of: event-ticketing
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: event-ticketing
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gateway-web
      ports:
        - protocol: TCP
          port: 8000
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-external-access
  namespace: event-ticketing
  labels:
    app.kubernetes.io/part-of: event-ticketing
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gateway-web
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
