---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-api-pdb
  namespace: event-ticketing
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: event-ticketing
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-web-pdb
  namespace: event-ticketing
  labels:
    app.kubernetes.io/name: gateway-web
    app.kubernetes.io/part-of: event-ticketing
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-web
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sweeper-pdb
  namespace: event-ticketing
  labels:
    app.kubernetes.io/name: sweeper
    app.kubernetes.io/part-of: event-ticketing
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sweeper
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: relay-pdb
  namespace: event-ticketing
  labels:
    app.kubernetes.io/name: relay
    app.kubernetes.io/part-of: event-ticketing
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: relay
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: admitter-pdb
  namespace: event-ticketing
  labels:
    app.kubernetes.io/name: admitter
    app.kubernetes.io/part-of: event-ticketing
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: admitter
